# Generated by Django 5.2.1 on 2025-05-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW_CAREER', 'Viewed Career'), ('CLICK_RESOURCE', 'Clicked Resource'), ('SAVE_CAREER', 'Saved Career'), ('SHARE_CAREER', 'Shared Career'), ('LOGIN', 'Logged In'), ('SEARCH', 'Performed Search')], max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CareerTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('demand_score', models.FloatField()),
                ('salary_trend', models.FloatField()),
                ('popularity', models.FloatField()),
                ('search_volume', models.IntegerField(default=0)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.career')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
