# Generated by Django 5.2.1 on 2025-05-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.TextField(blank=True)),
                ('hobby_categories', models.JSONField(default=list)),
                ('happy_activities', models.TextField(blank=True)),
                ('personal_vision', models.TextField(blank=True)),
                ('personality_type', models.CharField(blank=True, max_length=10)),
                ('career_goals', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.career')),
            ],
        ),
    ]
