# Generated by Django 5.2.1 on 2025-05-16 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='olevelrequirement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='utmerequirement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='olevelrequirement',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='olevel_requirements', to='course.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utmerequirement',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='utme_requirements', to='course.subject'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='olevelrequirement',
            unique_together={('school', 'course', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='utmerequirement',
            unique_together={('school', 'course', 'subject')},
        ),
    ]
