# Generated by Django 5.2.1 on 2025-06-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_olevelrequirement_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        # migrations.AddField(
        #     model_name='course',
        #     name='guid',
        #     field=models.CharField(default='', max_length=255, unique=True),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='school',
        #     name='guid',
        #     field=models.CharField(default=' ', max_length=255, unique=True),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='utmerequirement',
            name='required_status',
            field=models.CharField(choices=[('required', 'Required'), ('not_required', 'Not Required'), ('recommended', 'Recommended')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('name', 'school'), name='unique_course_per_school', violation_error_message='This course already exists in the specified school'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('name',), name='unique_school_name', violation_error_message='School with this name already exists'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('website',), name='unique_school_website', violation_error_message='School with this website already exists'),
        ),
    ]
