# Generated by Django 5.2.1 on 2025-05-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('recommended_skills', models.JSONField(default=list)),
                ('salary_range_min', models.IntegerField()),
                ('salary_range_max', models.IntegerField()),
                ('growth_outlook', models.FloatField()),
                ('demand_level', models.CharField(choices=[('HIGH', 'High Demand'), ('MEDIUM', 'Medium Demand'), ('LOW', 'Low Demand')], max_length=20)),
                ('education_requirements', models.TextField()),
                ('typical_pathway', models.JSONField(default=list)),
                ('related_hobbies', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('COURSE', 'Online Course'), ('BOOK', 'Book'), ('BOOT', 'Bootcamp'), ('DEG', 'Degree Program'), ('TUT', 'Tutorial')], max_length=10)),
                ('provider', models.CharField(max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='careers.career')),
            ],
        ),
    ]
