# Generated by Django 5.2.1 on 2025-06-28 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('salary_range', models.CharField(max_length=100)),
                ('job_outlook', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('global_ranking', models.IntegerField()),
                ('program_strengths', models.JSONField(default=list)),
                ('industry_connections', models.JSONField(default=list)),
                ('notable_alumni', models.JSONField(default=list)),
                ('internship_opportunities', models.BooleanField()),
                ('average_graduate_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree_name', models.CharField(max_length=200)),
                ('recommended_majors', models.JSONField(default=list)),
                ('typical_duration', models.CharField(max_length=50)),
                ('top_universities', models.JSONField(default=list)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careerpath')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exam_requirements', models.TextField()),
                ('average_salary_boost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marketability_boost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careerpath')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hobbies', models.JSONField(blank=True, default=list)),
                ('passions', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('vision', models.TextField(blank=True)),
                ('dream', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityCareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strength_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careerpath')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.university')),
            ],
            options={
                'unique_together': {('university', 'career_path')},
            },
        ),
    ]
