# Generated by Django 5.2.1 on 2025-05-12 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipconnection',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipconnection',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipmessage',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mentorship.mentorshipconnection'),
        ),
        migrations.AddField(
            model_name='mentorshipmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipconnection',
            unique_together={('mentor', 'mentee', 'career')},
        ),
    ]
