# Generated by Django 5.2.1 on 2025-05-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('CAREER_MATCH', 'Career Matching'), ('SKILL_EXTRACT', 'Skill Extraction'), ('PERSONALITY', 'Personality Analysis')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('performance_metrics', models.JSONField(default=dict)),
                ('training_data', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_start', models.DateTimeField()),
                ('training_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='RUNNING', max_length=20)),
                ('metrics', models.JSONField(default=dict)),
                ('logs', models.TextField(blank=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aimodelversion.aimodelversion')),
            ],
            options={
                'ordering': ['-training_start'],
            },
        ),
    ]
